apiVersion: v1
kind: Pod
metadata:
  name: simpleweb
spec:
  containers:
    - name: web-container
      image: nxgcloud/simpleweb:0.0.1
      ports:
        - containerPort: 5000
      command: [ "python", "/webapp/simpleweb.py"]
      env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: MY_NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
  restartPolicy: Never