apiVersion: v1
kind: Service
metadata:
  name: serviceall
spec:
  selector:
    serviceName: mySimpleService
  type: NodePort
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      protocol: TCP