apiVersion: v1
kind: Service
metadata:
  name: servicenp
spec:
  selector:
    app: simpleweb
  type: NodePort
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      nodePort: 30080
      protocol: TCP