apiVersion: v1
kind: Service
metadata:
  name: simpleservice
spec:
  selector:
    app: weba
  type: NodePort
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      nodePort: 30080
      protocol: TCP