apiVersion: apps/v1
kind: Deployment
metadata:
  name: weba-deployment
  labels:
    app: weba
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weba
  template:
    metadata:
      labels:
        app: weba
        serviceName: mySimpleService
    spec:
      containers:
      - name: weba
        image: nxgcloud/simpleweb:0.0.2
        ports:
        - containerPort: 5000
        command: [ "python", "/webapp/simpleweb.py"]
        env:
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: MY_NODE_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP

